# Generated by Django 3.2.8 on 2021-10-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211021_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2021-10-21'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default='2021-10-21'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
